### ISSUE TITLE
Failed to serialize collections containing only null elements in xlang mode

### ISSUE THREAD

**Issue by Handsome-cong** [apache/fury#2203]
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/fury/issues) and found no similar issues.

### Version

a37cc5513dd60c1995faa0998ac8c185d8337ce6

### Component(s)

Java

### Minimal reproduce step

``` java
Fury fury = Fury.builder().withLanguage(Language.XLANG).build();
ArrayList<String> strList = new ArrayList<>();
strList.add(null);
fury.serialize(strList);
```

### What did you expect to see?

The correct serialization into a byte sequence, and the ability to deserialize it back into a sequence containing only nulls.

### What did you see instead?

```
org.apache.fury.exception.ClassUnregisteredException: Class java.lang.Object is not registered
```

### Anything Else?

Different exception is thrown when RefTracing is enabled. It seems that void and Object are not registered by XtypeResolver by default.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by chaokunyang** [comment]
Hi @Handsome-cong , could you try latest code in main branch? I think it's fixed in that branch

**Comment by Handsome-cong** [comment]
HI @chaokunyang , I just tried it, and the issue is still there.

**Comment by chaokunyang** [comment]
@Handsome-cong This issue should be fixed now. Could you try it again
